# Generated by Django 3.0.6 on 2020-06-08 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=datetime.date(2020, 6, 8), verbose_name='Премьера в мире'),
        ),
    ]
