# Generated by Django 3.0.6 on 2020-06-08 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200608_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=datetime.datetime(2020, 6, 8, 16, 32, 55, 737735, tzinfo=utc), verbose_name='Премьера в мире'),
        ),
    ]
