# Generated by Django 3.0.6 on 2020-09-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200608_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieshots',
            options={'verbose_name': 'Кадры из фильма', 'verbose_name_plural': 'Кадр из фильма'},
        ),
    ]
