# Generated by Django 3.0.6 on 2020-09-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200914_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='fess_in_usa',
            new_name='fees_in_usa',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='fess_in_world',
            new_name='fees_in_world',
        ),
    ]
